import assert from 'node:assert/strict';
import { lstat, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { dirname, isAbsolute, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { marked } from 'marked';

export const skillNames = ['exhibit-publish', 'exhibit-setup'];
const repository = fileURLToPath(new URL('../', import.meta.url));
const installation = 'docs/user-guide/installation.md';
const generatedNotice = '<!-- Generated by pnpm skills:build. Edit src/skills, not this copy. -->';

async function rejectSymlinkAncestors(root, path) {
  let current = root;
  for (const segment of path.split('/')) {
    current = join(current, segment);
    try {
      assert.ok(!(await lstat(current)).isSymbolicLink(), `Symlink in bundle path: ${current}`);
    } catch (error) {
      if (error.code === 'ENOENT') return;
      throw error;
    }
  }
}

export async function inventory(root) {
  const files = new Map();
  let rootInfo;
  try {
    rootInfo = await lstat(root);
  } catch (error) {
    if (error.code === 'ENOENT') return files;
    throw error;
  }
  assert.ok(
    rootInfo.isDirectory() && !rootInfo.isSymbolicLink(),
    `Expected a bundle directory: ${root}`,
  );
  async function visit(path) {
    const info = await lstat(path);
    assert.ok(!info.isSymbolicLink(), `Skill bundles cannot contain symlinks: ${path}`);
    if (info.isDirectory()) {
      for (const entry of (await readdir(path)).sort()) await visit(join(path, entry));
    } else {
      assert.ok(info.isFile(), `Expected a regular bundle file: ${path}`);
      files.set(relative(root, path).split(sep).join('/'), await readFile(path));
    }
  }
  await visit(root);
  return files;
}

function localLinks(text, transform) {
  const replacements = new Map();
  marked.walkTokens(marked.lexer(text), (token) => {
    if (token.type === 'html') {
      assert.equal(
        token.raw.trim(),
        generatedNotice,
        'Use Markdown, not raw HTML, in skill bundles.',
      );
      return;
    }
    if (!['link', 'image'].includes(token.type)) return;
    if (/^(?:https?:|mailto:|\/\/)/i.test(token.href)) return;
    assert.ok(!/^[a-z][a-z0-9+.-]*:/i.test(token.href), `Unsupported reference URL: ${token.href}`);
    const changed = transform(token.href);
    if (changed !== token.href) {
      const original = `](${token.href})`;
      assert.ok(token.raw.includes(original), 'Use inline Markdown links for bundled resources.');
      replacements.set(token.raw, token.raw.replace(original, `](${changed})`));
    }
  });
  for (const [before, after] of replacements) text = text.replaceAll(before, after);
  return text;
}

export function validateBundle(files) {
  assert.ok(files.has('SKILL.md'), 'A skill requires SKILL.md');
  for (const [file, bytes] of files) {
    if (!file.endsWith('.md')) continue;
    localLinks(bytes.toString(), (href) => {
      const target = decodeURIComponent(href.split('#')[0]);
      if (!target) return href;
      const path = relative('/bundle', resolve('/bundle', dirname(file), target))
        .split(sep)
        .join('/');
      assert.ok(
        !isAbsolute(target) && !path.startsWith('../') && files.has(path),
        `${file}: missing or escaping bundled reference ${href}`,
      );
      return href;
    });
  }
}

export async function expectedBundles(root = repository) {
  for (const path of [installation, 'LICENSE', 'src/skills', 'src/plugin'])
    await rejectSymlinkAncestors(root, path);
  assert.deepEqual((await readdir(join(root, 'src/skills'))).sort(), [...skillNames].sort());
  const outputs = new Map();
  const license = await readFile(join(root, 'LICENSE'));
  const install = await readFile(join(root, installation));
  for (const name of skillNames) {
    const source = join(root, 'src/skills', name);
    const files = await inventory(source);
    assert.ok(
      !files.has('references/installation.md'),
      'Installation reference is generated from docs.',
    );
    files.set('references/installation.md', install);
    files.set('LICENSE', license);
    for (const [path, bytes] of files) {
      if (!path.endsWith('.md') || path === 'references/installation.md') continue;
      const text = localLinks(bytes.toString(), (href) => {
        const [target, ...fragment] = href.split('#');
        if (resolve(source, dirname(path), target) !== join(root, installation)) return href;
        const mapped = relative(dirname(path), 'references/installation.md').split(sep).join('/');
        return mapped + (fragment.length ? `#${fragment.join('#')}` : '');
      });
      files.set(path, Buffer.from(text));
    }
    const skill = files.get('SKILL.md').toString();
    assert.ok(skill.startsWith(`---\nname: ${name}\n`), `Invalid skill identity: ${name}`);
    files.set('SKILL.md', Buffer.from(skill.replace('\n---\n', `\n---\n\n${generatedNotice}\n`)));
    validateBundle(files);
    for (const [path, bytes] of files) {
      outputs.set(`skills/${name}/${path}`, bytes);
      outputs.set(`plugins/exhibit/skills/${name}/${path}`, bytes);
    }
  }
  const manifests = await inventory(join(root, 'src/plugin'));
  for (const provider of ['codex', 'claude', 'cursor'])
    assert.ok(manifests.has(`.${provider}-plugin/plugin.json`), `Missing ${provider} manifest`);
  for (const [path, bytes] of manifests) {
    const manifest = JSON.parse(bytes.toString());
    assert.equal(manifest.name, 'exhibit');
    outputs.set(`plugins/exhibit/${path}`, bytes);
  }
  outputs.set('plugins/exhibit/LICENSE', license);
  return outputs;
}

export async function packageSkills({ root = repository, check = false } = {}) {
  // Resolve and validate every input before modifying either generated destination.
  const expected = await expectedBundles(root);
  for (const directory of ['skills', 'plugins/exhibit'])
    await rejectSymlinkAncestors(root, directory);
  const actual = new Map();
  for (const directory of ['skills', 'plugins/exhibit'])
    for (const [path, bytes] of await inventory(join(root, directory)))
      actual.set(`${directory}/${path}`, bytes);
  const changed = [...expected].filter(
    ([path, bytes]) => !actual.has(path) || !bytes.equals(actual.get(path)),
  );
  const stale = [...actual.keys()].filter((path) => !expected.has(path));
  if (check) {
    assert.ok(
      !changed.length && !stale.length,
      `Generated skills are stale; run pnpm skills:build.\n${[...changed.map(([path]) => path), ...stale].join('\n')}`,
    );
    return;
  }
  for (const [path, bytes] of changed) {
    await mkdir(dirname(join(root, path)), { recursive: true });
    await writeFile(join(root, path), bytes);
  }
  for (const path of stale) await rm(join(root, path));
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  assert.ok(
    process.argv.slice(2).every((arg) => arg === '--check'),
    'Only --check is supported.',
  );
  await packageSkills({ check: process.argv.includes('--check') });
  process.stdout.write('Standalone and plugin skill bundles verified.\n');
}
